name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build with Docker
        run: |
          # Build the Docker image
          docker build -t guacamole-player .

          # Create a temporary container
          docker create --name temp-container guacamole-player

          # Copy the built application from the container to the dist directory
          docker cp temp-container:/usr/share/nginx/html/. ./dist/

          # Remove the temporary container
          docker rm temp-container

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
